stages:
 - test
 - build
 - release
 - deploy

cache:
  paths:
  - node_modules/

test:
  stage: test
  image: node:8-alpine
  before_script:
      - npm install
  script:
   - npm run cov
lint:
  stage: test
  image: node:8-alpine
  before_script:
      - npm install
  script:
   - npm run lint:style

build:
  stage: build
  script:
    - echo 'deployd!'
   #- npm run build

release:
  stage: release
  image: docker:latest
  only:
    - tag
  services:
    - docker:dind
  script:
    - echo 'release!'
#  before_script:
#      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#  script:
#      - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:$CI_COMMIT_TAG --pull .
#      - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:$CI_COMMIT_TAG
#  after_script:
#    - docker logout ${CI_REGISTRY}

deploy:
  stage: deploy
  script:
  - echo 'deployd!'
  only:
  - master
